name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - k3fair
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: Name and email
    validations:
      required: false
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Please describe the issue
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional info
      description: Please provide any relevant information such as your OS, Python version, Spyder version
    validations:
      required: false  
